// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/video/build.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 切割策略
type SplitStrategy int32

const (
	SplitStrategy_SIZE SplitStrategy = 0
	SplitStrategy_TIME SplitStrategy = 1
)

var SplitStrategy_name = map[int32]string{
	0: "SIZE",
	1: "TIME",
}

var SplitStrategy_value = map[string]int32{
	"SIZE": 0,
	"TIME": 1,
}

func (x SplitStrategy) String() string {
	return proto.EnumName(SplitStrategy_name, int32(x))
}

func (SplitStrategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{0}
}

// 构建回复
type BuildResponse struct {
	// 状态
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 任务ID
	TaskID               string   `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{0}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BuildResponse) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

// 合并请求
type CombineRequest struct {
	// 视频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Video                []string `protobuf:"bytes,1,rep,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CombineRequest) Reset()         { *m = CombineRequest{} }
func (m *CombineRequest) String() string { return proto.CompactTextString(m) }
func (*CombineRequest) ProtoMessage()    {}
func (*CombineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{1}
}

func (m *CombineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombineRequest.Unmarshal(m, b)
}
func (m *CombineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombineRequest.Marshal(b, m, deterministic)
}
func (m *CombineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombineRequest.Merge(m, src)
}
func (m *CombineRequest) XXX_Size() int {
	return xxx_messageInfo_CombineRequest.Size(m)
}
func (m *CombineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CombineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CombineRequest proto.InternalMessageInfo

func (m *CombineRequest) GetVideo() []string {
	if m != nil {
		return m.Video
	}
	return nil
}

// 切割请求
type SplitRequest struct {
	// 视频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Video string `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	// 切割策略
	Strategy SplitStrategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=video.SplitStrategy" json:"strategy,omitempty"`
	// 切割因子，strategy=SIZE时，此值的单位是字节，strategy=TIME时，此值的单位时秒
	Factor               int32    `protobuf:"varint,3,opt,name=factor,proto3" json:"factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitRequest) Reset()         { *m = SplitRequest{} }
func (m *SplitRequest) String() string { return proto.CompactTextString(m) }
func (*SplitRequest) ProtoMessage()    {}
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{2}
}

func (m *SplitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitRequest.Unmarshal(m, b)
}
func (m *SplitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitRequest.Marshal(b, m, deterministic)
}
func (m *SplitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitRequest.Merge(m, src)
}
func (m *SplitRequest) XXX_Size() int {
	return xxx_messageInfo_SplitRequest.Size(m)
}
func (m *SplitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SplitRequest proto.InternalMessageInfo

func (m *SplitRequest) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *SplitRequest) GetStrategy() SplitStrategy {
	if m != nil {
		return m.Strategy
	}
	return SplitStrategy_SIZE
}

func (m *SplitRequest) GetFactor() int32 {
	if m != nil {
		return m.Factor
	}
	return 0
}

//图片
type Image struct {
	// 图片文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// 时间戳的偏移值, 单位为毫秒
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// 持续时间, 单位为毫秒,超出此时间的内容会被截断
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{3}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Image) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Image) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

//音频
type Audio struct {
	// 音频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// 时间戳的偏移值, 单位为毫秒
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// 持续时间, 单位为毫秒,超出此时间的内容会被截断
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audio) Reset()         { *m = Audio{} }
func (m *Audio) String() string { return proto.CompactTextString(m) }
func (*Audio) ProtoMessage()    {}
func (*Audio) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{4}
}

func (m *Audio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audio.Unmarshal(m, b)
}
func (m *Audio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audio.Marshal(b, m, deterministic)
}
func (m *Audio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audio.Merge(m, src)
}
func (m *Audio) XXX_Size() int {
	return xxx_messageInfo_Audio.Size(m)
}
func (m *Audio) XXX_DiscardUnknown() {
	xxx_messageInfo_Audio.DiscardUnknown(m)
}

var xxx_messageInfo_Audio proto.InternalMessageInfo

func (m *Audio) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Audio) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Audio) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// 渲染请求
type RenderRequest struct {
	// 图片集
	Image []*Image `protobuf:"bytes,1,rep,name=image,proto3" json:"image,omitempty"`
	// 音频集
	Audio                []*Audio `protobuf:"bytes,2,rep,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderRequest) Reset()         { *m = RenderRequest{} }
func (m *RenderRequest) String() string { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()    {}
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{5}
}

func (m *RenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderRequest.Unmarshal(m, b)
}
func (m *RenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderRequest.Marshal(b, m, deterministic)
}
func (m *RenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderRequest.Merge(m, src)
}
func (m *RenderRequest) XXX_Size() int {
	return xxx_messageInfo_RenderRequest.Size(m)
}
func (m *RenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderRequest proto.InternalMessageInfo

func (m *RenderRequest) GetImage() []*Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *RenderRequest) GetAudio() []*Audio {
	if m != nil {
		return m.Audio
	}
	return nil
}

func init() {
	proto.RegisterEnum("video.SplitStrategy", SplitStrategy_name, SplitStrategy_value)
	proto.RegisterType((*BuildResponse)(nil), "video.BuildResponse")
	proto.RegisterType((*CombineRequest)(nil), "video.CombineRequest")
	proto.RegisterType((*SplitRequest)(nil), "video.SplitRequest")
	proto.RegisterType((*Image)(nil), "video.Image")
	proto.RegisterType((*Audio)(nil), "video.Audio")
	proto.RegisterType((*RenderRequest)(nil), "video.RenderRequest")
}

func init() {
	proto.RegisterFile("proto/video/build.proto", fileDescriptor_475d49d3c86cca58)
}

var fileDescriptor_475d49d3c86cca58 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xcf, 0x6b, 0xdb, 0x30,
	0x14, 0x8e, 0xe2, 0xd8, 0x4b, 0x5e, 0xe2, 0x10, 0xb4, 0x6c, 0x33, 0x39, 0x19, 0x8f, 0x0d, 0xb3,
	0x43, 0x32, 0xbc, 0x31, 0x76, 0xdd, 0x8f, 0x1c, 0x7c, 0xd8, 0x0a, 0x72, 0xa1, 0xd0, 0x9b, 0x52,
	0xcb, 0xa9, 0x68, 0x62, 0xa5, 0x96, 0x5c, 0xe8, 0x5f, 0xd5, 0x7f, 0xb1, 0x48, 0x96, 0x43, 0x0c,
	0x2d, 0xbd, 0xf4, 0xa6, 0xa7, 0xef, 0xfb, 0xde, 0xfb, 0xde, 0x0f, 0xf8, 0x70, 0xa8, 0x84, 0x12,
	0xab, 0x3b, 0x9e, 0x33, 0xb1, 0xda, 0xd4, 0x7c, 0x97, 0x2f, 0xcd, 0x0f, 0x76, 0xcd, 0xd7, 0x22,
	0x38, 0xc5, 0xe5, 0x35, 0xad, 0x98, 0x25, 0x44, 0xff, 0xc1, 0xff, 0xad, 0xf9, 0x84, 0xc9, 0x83,
	0x28, 0x25, 0xc3, 0x9f, 0xc0, 0x93, 0x8a, 0xaa, 0x5a, 0x06, 0x28, 0x44, 0xf1, 0x38, 0xf1, 0x97,
	0x46, 0xb5, 0xcc, 0xcc, 0x27, 0xb1, 0x20, 0x7e, 0x0f, 0x9e, 0xa2, 0xf2, 0x26, 0xfd, 0x1b, 0xf4,
	0x43, 0x14, 0x8f, 0x88, 0x8d, 0xa2, 0xcf, 0x30, 0xfd, 0x23, 0xf6, 0x1b, 0x5e, 0x32, 0xc2, 0x6e,
	0x6b, 0x26, 0x15, 0x9e, 0x43, 0x63, 0x22, 0x40, 0xa1, 0x13, 0x8f, 0x48, 0x13, 0x44, 0x25, 0x4c,
	0xb2, 0xc3, 0x8e, 0xab, 0x27, 0x58, 0xe8, 0xc8, 0xc2, 0x5f, 0x61, 0x28, 0x55, 0x45, 0x15, 0xdb,
	0xde, 0x9b, 0x3a, 0xd3, 0x64, 0xde, 0xda, 0xd1, 0xe2, 0xcc, 0x62, 0xe4, 0xc8, 0xd2, 0xbe, 0x0a,
	0x7a, 0xa5, 0x44, 0x15, 0x38, 0x21, 0x8a, 0x5d, 0x62, 0xa3, 0xe8, 0x0c, 0xdc, 0x74, 0x4f, 0xb7,
	0x0c, 0x63, 0x18, 0x14, 0x7c, 0xc7, 0x6c, 0x1d, 0xf3, 0xd6, 0x22, 0x51, 0x14, 0x92, 0x29, 0x53,
	0xc4, 0x21, 0x36, 0xc2, 0x0b, 0x18, 0xe6, 0x75, 0x45, 0x15, 0x17, 0xa5, 0x49, 0xe7, 0x90, 0x63,
	0xac, 0x13, 0xfe, 0xaa, 0x73, 0x2e, 0x5e, 0x2d, 0xe1, 0x05, 0xf8, 0x84, 0x95, 0x39, 0xab, 0xda,
	0x91, 0x44, 0xe0, 0x72, 0x6d, 0xd9, 0x0c, 0x6e, 0x9c, 0x4c, 0x6c, 0xe7, 0xa6, 0x0d, 0xd2, 0x40,
	0x9a, 0x43, 0xb5, 0x8b, 0xa0, 0xdf, 0xe1, 0x18, 0x67, 0xa4, 0x81, 0xbe, 0x7c, 0x04, 0xbf, 0x33,
	0x2d, 0x3c, 0x84, 0x41, 0x96, 0x5e, 0xae, 0x67, 0x3d, 0xfd, 0x3a, 0x4f, 0xff, 0xad, 0x67, 0x28,
	0x79, 0x40, 0xe0, 0x9a, 0x43, 0xc0, 0x3f, 0xe1, 0x8d, 0xdd, 0x20, 0x7e, 0x67, 0xd3, 0x75, 0x37,
	0xba, 0x68, 0x77, 0xd0, 0x39, 0x9c, 0xa8, 0x87, 0xbf, 0x83, 0x6b, 0x0a, 0xe1, 0xb7, 0xa7, 0x4b,
	0x7a, 0x49, 0xf5, 0x03, 0xbc, 0xa6, 0x6f, 0xdc, 0x32, 0x3a, 0x63, 0x78, 0x4e, 0xb7, 0xf1, 0xcc,
	0x01, 0x7f, 0x7b, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x61, 0x80, 0x82, 0xb8, 0xfc, 0x02, 0x00, 0x00,
}
