// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/video/build.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 切割策略
type SplitStrategy int32

const (
	SplitStrategy_SIZE SplitStrategy = 0
	SplitStrategy_TIME SplitStrategy = 1
)

var SplitStrategy_name = map[int32]string{
	0: "SIZE",
	1: "TIME",
}

var SplitStrategy_value = map[string]int32{
	"SIZE": 0,
	"TIME": 1,
}

func (x SplitStrategy) String() string {
	return proto.EnumName(SplitStrategy_name, int32(x))
}

func (SplitStrategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{0}
}

// 构建回复
type BuildResponse struct {
	// 状态
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 任务ID
	TaskID               string   `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{0}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BuildResponse) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

// 合并请求
type CombineRequest struct {
	// 视频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Video                []string `protobuf:"bytes,1,rep,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CombineRequest) Reset()         { *m = CombineRequest{} }
func (m *CombineRequest) String() string { return proto.CompactTextString(m) }
func (*CombineRequest) ProtoMessage()    {}
func (*CombineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{1}
}

func (m *CombineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombineRequest.Unmarshal(m, b)
}
func (m *CombineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombineRequest.Marshal(b, m, deterministic)
}
func (m *CombineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombineRequest.Merge(m, src)
}
func (m *CombineRequest) XXX_Size() int {
	return xxx_messageInfo_CombineRequest.Size(m)
}
func (m *CombineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CombineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CombineRequest proto.InternalMessageInfo

func (m *CombineRequest) GetVideo() []string {
	if m != nil {
		return m.Video
	}
	return nil
}

// 切割请求
type SplitRequest struct {
	// 视频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Video string `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	// 切割策略
	Strategy SplitStrategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=video.SplitStrategy" json:"strategy,omitempty"`
	// 切割因子，strategy=SIZE时，此值的单位是字节，strategy=TIME时，此值的单位时秒
	Factor               int32    `protobuf:"varint,3,opt,name=factor,proto3" json:"factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitRequest) Reset()         { *m = SplitRequest{} }
func (m *SplitRequest) String() string { return proto.CompactTextString(m) }
func (*SplitRequest) ProtoMessage()    {}
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{2}
}

func (m *SplitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitRequest.Unmarshal(m, b)
}
func (m *SplitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitRequest.Marshal(b, m, deterministic)
}
func (m *SplitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitRequest.Merge(m, src)
}
func (m *SplitRequest) XXX_Size() int {
	return xxx_messageInfo_SplitRequest.Size(m)
}
func (m *SplitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SplitRequest proto.InternalMessageInfo

func (m *SplitRequest) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *SplitRequest) GetStrategy() SplitStrategy {
	if m != nil {
		return m.Strategy
	}
	return SplitStrategy_SIZE
}

func (m *SplitRequest) GetFactor() int32 {
	if m != nil {
		return m.Factor
	}
	return 0
}

type Picture struct {
	// 图片文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// 图片在视频中的时间戳, 单位为毫秒
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{3}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Picture) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// 渲染请求
type RenderRequest struct {
	// 图片集
	Picture []*Picture `protobuf:"bytes,1,rep,name=picture,proto3" json:"picture,omitempty"`
	// 音频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Audio                string   `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderRequest) Reset()         { *m = RenderRequest{} }
func (m *RenderRequest) String() string { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()    {}
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{4}
}

func (m *RenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderRequest.Unmarshal(m, b)
}
func (m *RenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderRequest.Marshal(b, m, deterministic)
}
func (m *RenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderRequest.Merge(m, src)
}
func (m *RenderRequest) XXX_Size() int {
	return xxx_messageInfo_RenderRequest.Size(m)
}
func (m *RenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderRequest proto.InternalMessageInfo

func (m *RenderRequest) GetPicture() []*Picture {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *RenderRequest) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

// 绘制请求
type DrawRequest struct {
	// 笔迹文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Pen string `protobuf:"bytes,1,opt,name=pen,proto3" json:"pen,omitempty"`
	// 音频文件地址
	// 网络地址使用http://或https://前缀
	// 内置存储使用file://前缀
	Audio string `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	// 笔迹数据解析器
	Parser               string   `protobuf:"bytes,3,opt,name=parser,proto3" json:"parser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawRequest) Reset()         { *m = DrawRequest{} }
func (m *DrawRequest) String() string { return proto.CompactTextString(m) }
func (*DrawRequest) ProtoMessage()    {}
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d49d3c86cca58, []int{5}
}

func (m *DrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawRequest.Unmarshal(m, b)
}
func (m *DrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawRequest.Marshal(b, m, deterministic)
}
func (m *DrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawRequest.Merge(m, src)
}
func (m *DrawRequest) XXX_Size() int {
	return xxx_messageInfo_DrawRequest.Size(m)
}
func (m *DrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawRequest proto.InternalMessageInfo

func (m *DrawRequest) GetPen() string {
	if m != nil {
		return m.Pen
	}
	return ""
}

func (m *DrawRequest) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

func (m *DrawRequest) GetParser() string {
	if m != nil {
		return m.Parser
	}
	return ""
}

func init() {
	proto.RegisterEnum("video.SplitStrategy", SplitStrategy_name, SplitStrategy_value)
	proto.RegisterType((*BuildResponse)(nil), "video.BuildResponse")
	proto.RegisterType((*CombineRequest)(nil), "video.CombineRequest")
	proto.RegisterType((*SplitRequest)(nil), "video.SplitRequest")
	proto.RegisterType((*Picture)(nil), "video.Picture")
	proto.RegisterType((*RenderRequest)(nil), "video.RenderRequest")
	proto.RegisterType((*DrawRequest)(nil), "video.DrawRequest")
}

func init() {
	proto.RegisterFile("proto/video/build.proto", fileDescriptor_475d49d3c86cca58)
}

var fileDescriptor_475d49d3c86cca58 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5f, 0xef, 0xd2, 0x30,
	0x14, 0xa5, 0x8e, 0x0d, 0x76, 0x71, 0x84, 0x54, 0xd4, 0x85, 0xf8, 0xb0, 0xcc, 0x68, 0x16, 0x1f,
	0xc0, 0x4c, 0x63, 0x7c, 0xf1, 0x45, 0xe1, 0x81, 0x07, 0xd4, 0x74, 0x3e, 0xf9, 0x56, 0x58, 0xc5,
	0x46, 0xf6, 0xc7, 0xb6, 0xd3, 0xf8, 0x79, 0xfd, 0x22, 0xa6, 0x5d, 0x87, 0x2c, 0x81, 0xfc, 0xde,
	0x7a, 0xef, 0x3d, 0xa7, 0xe7, 0xf4, 0xdc, 0xc2, 0xe3, 0x5a, 0x54, 0xaa, 0x5a, 0xfd, 0xe2, 0x39,
	0xab, 0x56, 0xfb, 0x86, 0x9f, 0xf2, 0xa5, 0xe9, 0x60, 0xd7, 0xb4, 0x16, 0xe1, 0xe5, 0x5c, 0x7e,
	0xa7, 0x82, 0x59, 0x40, 0xfc, 0x11, 0x82, 0xf7, 0x1a, 0x4f, 0x98, 0xac, 0xab, 0x52, 0x32, 0xfc,
	0x0c, 0x3c, 0xa9, 0xa8, 0x6a, 0x64, 0x88, 0x22, 0x94, 0x4c, 0xd2, 0x60, 0x69, 0x58, 0xcb, 0xcc,
	0x34, 0x89, 0x1d, 0xe2, 0x47, 0xe0, 0x29, 0x2a, 0x7f, 0x6c, 0xd7, 0xe1, 0xbd, 0x08, 0x25, 0x3e,
	0xb1, 0x55, 0xfc, 0x1c, 0xa6, 0x1f, 0xaa, 0x62, 0xcf, 0x4b, 0x46, 0xd8, 0xcf, 0x86, 0x49, 0x85,
	0xe7, 0xd0, 0x9a, 0x08, 0x51, 0xe4, 0x24, 0x3e, 0x69, 0x8b, 0xb8, 0x84, 0xfb, 0x59, 0x7d, 0xe2,
	0xea, 0x0a, 0x0a, 0x9d, 0x51, 0xf8, 0x25, 0x8c, 0xa5, 0x12, 0x54, 0xb1, 0xe3, 0x1f, 0xa3, 0x33,
	0x4d, 0xe7, 0x9d, 0x1d, 0x4d, 0xce, 0xec, 0x8c, 0x9c, 0x51, 0xda, 0xd7, 0x37, 0x7a, 0x50, 0x95,
	0x08, 0x9d, 0x08, 0x25, 0x2e, 0xb1, 0x55, 0xfc, 0x0e, 0x46, 0x9f, 0xf9, 0x41, 0x35, 0x82, 0x69,
	0x29, 0x5e, 0xd0, 0x23, 0xeb, 0xa4, 0x4c, 0x81, 0x9f, 0x80, 0xaf, 0x78, 0xc1, 0xa4, 0xa2, 0x45,
	0x6d, 0xb4, 0x1c, 0xf2, 0xbf, 0x11, 0x7f, 0x82, 0x80, 0xb0, 0x32, 0x67, 0xa2, 0xf3, 0x9b, 0xc0,
	0xa8, 0x6e, 0xef, 0x33, 0xef, 0x9a, 0xa4, 0x53, 0x6b, 0xcc, 0xaa, 0x90, 0x6e, 0xac, 0xe5, 0x68,
	0x93, 0xf3, 0xca, 0x06, 0xd5, 0x16, 0xf1, 0x0e, 0x26, 0x6b, 0x41, 0x7f, 0x77, 0xd7, 0xcd, 0xc0,
	0xa9, 0x59, 0x69, 0x1d, 0xe9, 0xe3, 0x75, 0x9a, 0x7e, 0x5e, 0x4d, 0x85, 0x64, 0xed, 0xf3, 0x7c,
	0x62, 0xab, 0x17, 0x4f, 0x21, 0xe8, 0x25, 0x82, 0xc7, 0x30, 0xcc, 0xb6, 0x5f, 0x37, 0xb3, 0x81,
	0x3e, 0x7d, 0xd9, 0xee, 0x36, 0x33, 0x94, 0xfe, 0x45, 0xe0, 0x9a, 0x65, 0xe3, 0xb7, 0x30, 0xb2,
	0x5b, 0xc2, 0x0f, 0xad, 0xef, 0xfe, 0xd6, 0x16, 0x5d, 0xce, 0xbd, 0xcf, 0x11, 0x0f, 0xf0, 0x6b,
	0x70, 0x8d, 0x10, 0x7e, 0x70, 0xb9, 0x88, 0xbb, 0x58, 0x6f, 0xc0, 0x6b, 0xe3, 0xc3, 0x1d, 0xa2,
	0x97, 0xe6, 0x4d, 0x5e, 0x0a, 0x43, 0x9d, 0x12, 0xc6, 0x76, 0x7e, 0x11, 0xd9, 0x2d, 0xce, 0xde,
	0x33, 0x1f, 0xfb, 0xd5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xb3, 0xfe, 0xc2, 0x14, 0x03,
	0x00, 0x00,
}
