// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/video/cache.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 缓存回复
type CacheResponse struct {
	// 状态
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 文件地址，以file://为前缀
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheResponse) Reset()         { *m = CacheResponse{} }
func (m *CacheResponse) String() string { return proto.CompactTextString(m) }
func (*CacheResponse) ProtoMessage()    {}
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a25840d8cd57916, []int{0}
}

func (m *CacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheResponse.Unmarshal(m, b)
}
func (m *CacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheResponse.Marshal(b, m, deterministic)
}
func (m *CacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheResponse.Merge(m, src)
}
func (m *CacheResponse) XXX_Size() int {
	return xxx_messageInfo_CacheResponse.Size(m)
}
func (m *CacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CacheResponse proto.InternalMessageInfo

func (m *CacheResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CacheResponse) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

// 保存请求
type SaveRequest struct {
	// 字节数据
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 文件扩展名，不包含.号
	Extension            string   `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a25840d8cd57916, []int{1}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SaveRequest) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

// 保存请求
type StreamSaveRequest struct {
	// 字节数据
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 文件扩展名，不包含.号
	Extension string `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	// 整个数据包的大小
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamSaveRequest) Reset()         { *m = StreamSaveRequest{} }
func (m *StreamSaveRequest) String() string { return proto.CompactTextString(m) }
func (*StreamSaveRequest) ProtoMessage()    {}
func (*StreamSaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a25840d8cd57916, []int{2}
}

func (m *StreamSaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSaveRequest.Unmarshal(m, b)
}
func (m *StreamSaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSaveRequest.Marshal(b, m, deterministic)
}
func (m *StreamSaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSaveRequest.Merge(m, src)
}
func (m *StreamSaveRequest) XXX_Size() int {
	return xxx_messageInfo_StreamSaveRequest.Size(m)
}
func (m *StreamSaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSaveRequest proto.InternalMessageInfo

func (m *StreamSaveRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamSaveRequest) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *StreamSaveRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*CacheResponse)(nil), "video.CacheResponse")
	proto.RegisterType((*SaveRequest)(nil), "video.SaveRequest")
	proto.RegisterType((*StreamSaveRequest)(nil), "video.StreamSaveRequest")
}

func init() {
	proto.RegisterFile("proto/video/cache.proto", fileDescriptor_3a25840d8cd57916)
}

var fileDescriptor_3a25840d8cd57916 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x50, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x35, 0xf6, 0x03, 0x3a, 0xb5, 0x07, 0x07, 0xc1, 0x50, 0x3c, 0x2c, 0x01, 0x21, 0xa7, 0x2d,
	0xac, 0x3f, 0x40, 0xc1, 0x9b, 0xc7, 0xec, 0xc9, 0x63, 0xec, 0x8e, 0x34, 0xa0, 0x9b, 0xba, 0x93,
	0x16, 0x11, 0xfc, 0xef, 0x92, 0x71, 0x75, 0x55, 0xf0, 0xd4, 0xdb, 0xe3, 0xcd, 0x7b, 0x6f, 0x66,
	0x1e, 0x9c, 0x6f, 0xbb, 0x98, 0xe2, 0x6a, 0x1f, 0x1a, 0x8a, 0xab, 0xb5, 0x5f, 0x6f, 0xa8, 0x14,
	0x06, 0x27, 0x42, 0x2d, 0xf5, 0xcf, 0x39, 0x6f, 0x7c, 0x47, 0xcd, 0xa7, 0xc0, 0xdc, 0xc1, 0xe2,
	0x36, 0xeb, 0x1d, 0xf1, 0x36, 0xb6, 0x4c, 0x78, 0x09, 0x53, 0x4e, 0x3e, 0xed, 0x58, 0xab, 0x42,
	0xd9, 0x79, 0xb5, 0x28, 0xc5, 0x55, 0xd6, 0x42, 0xba, 0x7e, 0x88, 0x08, 0xe3, 0xc7, 0xf0, 0x44,
	0xfa, 0xb8, 0x50, 0x76, 0xe6, 0x04, 0x9b, 0x6b, 0x98, 0xd7, 0x7e, 0x4f, 0x8e, 0x5e, 0x76, 0xc4,
	0x29, 0x4b, 0x1a, 0x9f, 0xbc, 0xe4, 0x9c, 0x38, 0xc1, 0x78, 0x01, 0x33, 0x7a, 0x4d, 0xd4, 0x72,
	0x88, 0x6d, 0xef, 0x1d, 0x08, 0x73, 0x0f, 0xa7, 0x75, 0xea, 0xc8, 0x3f, 0x1f, 0x14, 0x93, 0x1d,
	0x1c, 0xde, 0x48, 0x8f, 0x0a, 0x65, 0x47, 0x4e, 0x70, 0xf5, 0x0e, 0x13, 0xf9, 0x13, 0x2b, 0x18,
	0xe7, 0x74, 0xc4, 0xaf, 0xbf, 0x86, 0x55, 0xcb, 0xb3, 0x9e, 0xfb, 0xd5, 0x88, 0x39, 0xc2, 0x1b,
	0x80, 0xe1, 0x2e, 0xd4, 0xdf, 0x8d, 0xfc, 0x39, 0xf5, 0x3f, 0xbf, 0x55, 0x0f, 0x53, 0x69, 0xfb,
	0xea, 0x23, 0x00, 0x00, 0xff, 0xff, 0x32, 0x56, 0x99, 0xac, 0xa9, 0x01, 0x00, 0x00,
}
