// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/video/cache.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Cache service

type CacheService interface {
	// 将数据转存为文件
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*CacheResponse, error)
}

type cacheService struct {
	c    client.Client
	name string
}

func NewCacheService(name string, c client.Client) CacheService {
	return &cacheService{
		c:    c,
		name: name,
	}
}

func (c *cacheService) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*CacheResponse, error) {
	req := c.c.NewRequest(c.name, "Cache.Save", in)
	out := new(CacheResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cache service

type CacheHandler interface {
	// 将数据转存为文件
	Save(context.Context, *SaveRequest, *CacheResponse) error
}

func RegisterCacheHandler(s server.Server, hdlr CacheHandler, opts ...server.HandlerOption) error {
	type cache interface {
		Save(ctx context.Context, in *SaveRequest, out *CacheResponse) error
	}
	type Cache struct {
		cache
	}
	h := &cacheHandler{hdlr}
	return s.Handle(s.NewHandler(&Cache{h}, opts...))
}

type cacheHandler struct {
	CacheHandler
}

func (h *cacheHandler) Save(ctx context.Context, in *SaveRequest, out *CacheResponse) error {
	return h.CacheHandler.Save(ctx, in, out)
}
