// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/video/task.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Task service

type TaskService interface {
	// 查询
	Query(ctx context.Context, in *QueryRequest, opts ...client.CallOption) (*QueryResponse, error)
	// 取消
	Cancel(ctx context.Context, in *CancelRequest, opts ...client.CallOption) (*CancelResponse, error)
	// 取走合成完的文件，取走后文件将被删除
	Take(ctx context.Context, in *TakeRequest, opts ...client.CallOption) (*TakeResponse, error)
}

type taskService struct {
	c    client.Client
	name string
}

func NewTaskService(name string, c client.Client) TaskService {
	return &taskService{
		c:    c,
		name: name,
	}
}

func (c *taskService) Query(ctx context.Context, in *QueryRequest, opts ...client.CallOption) (*QueryResponse, error) {
	req := c.c.NewRequest(c.name, "Task.Query", in)
	out := new(QueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Cancel(ctx context.Context, in *CancelRequest, opts ...client.CallOption) (*CancelResponse, error) {
	req := c.c.NewRequest(c.name, "Task.Cancel", in)
	out := new(CancelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Take(ctx context.Context, in *TakeRequest, opts ...client.CallOption) (*TakeResponse, error) {
	req := c.c.NewRequest(c.name, "Task.Take", in)
	out := new(TakeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Task service

type TaskHandler interface {
	// 查询
	Query(context.Context, *QueryRequest, *QueryResponse) error
	// 取消
	Cancel(context.Context, *CancelRequest, *CancelResponse) error
	// 取走合成完的文件，取走后文件将被删除
	Take(context.Context, *TakeRequest, *TakeResponse) error
}

func RegisterTaskHandler(s server.Server, hdlr TaskHandler, opts ...server.HandlerOption) error {
	type task interface {
		Query(ctx context.Context, in *QueryRequest, out *QueryResponse) error
		Cancel(ctx context.Context, in *CancelRequest, out *CancelResponse) error
		Take(ctx context.Context, in *TakeRequest, out *TakeResponse) error
	}
	type Task struct {
		task
	}
	h := &taskHandler{hdlr}
	return s.Handle(s.NewHandler(&Task{h}, opts...))
}

type taskHandler struct {
	TaskHandler
}

func (h *taskHandler) Query(ctx context.Context, in *QueryRequest, out *QueryResponse) error {
	return h.TaskHandler.Query(ctx, in, out)
}

func (h *taskHandler) Cancel(ctx context.Context, in *CancelRequest, out *CancelResponse) error {
	return h.TaskHandler.Cancel(ctx, in, out)
}

func (h *taskHandler) Take(ctx context.Context, in *TakeRequest, out *TakeResponse) error {
	return h.TaskHandler.Take(ctx, in, out)
}
